# 应用服务 WEB 访问端口
server:
  port: 8080

spring:
  thymeleaf:
    prefix: classpath:/static/
    suffix: .html
    servlet:
      content-type: text/html
  application:
    name: octopus
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 2000
    jedis:
      pool:
        max-active: 10
        max-idle: 6
        min-idle: 2
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/spring
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    view:
      suffix: .html

cache:
  #  type 可选 redis,map
  type: redis

#下面这些内容是为了让MyBatis映射
#指定Mybatis的Mapper文件
mybatis:
  mapper-locations: classpath:mappers/*xml
  #指定Mybatis的实体目录
  type-aliases-package: top.ninng.octopus.mybatis.entity


